#!/usr/bin/env bash

# Always empty the dest folder, as we post-process it to add album artwork which throws everything off.

# no trailing slashes - force rsync to copy folder
set -e

SRC="/nfs/iTunes Media Folder/Music"
DEST="/Volumes/GILMEDIA/music"

artists=(
   "Alcest"
   "Alison's Halo"
   "All Girl Summer Fun Band"
   "All Natural Lemon & Lime Flavors"
   "Antônio Carlos Jobim"
   "Asobi Seksu/Asobi Seksu"
   "Asobi Seksu/Citrus Remixes"
   "Asobi Seksu/Citrus"
   "Asobi Seksu/Sportfuck"
   "Asobi Seksu/Unknown Album"
   "Astrud Gilberto"
   "Astrud Gilberto_Walter Wanderley"
   "Bark Psychosis"
   "Boris/Akuma No Uta"
   "Boris/Heavy Rocks"
   "Boris/Pink"
   "Bowery Electric"
   "Broken Bells"
   "Capsule"
   "Caribou"
   "Carissa's Wierd"
   "Carved in Stone"
   "Courtney Barnett"
   "Creedence Clearwater Revival"
   "David Gilman"
   "Dead Mellotron"
   "Dead or Alive"
   "Death From Above 1979"
   "Dinosaur Jr_"
   "Drop Nineteens"
   "Electrelane/No Shouts No Calls"
   "Electrelane/The Power Out"
   "Electric Six/Fire"
   "Electric Six/I Shall Exterminate Everything Around Me That Restricts Me from Being the Master"
   "Electric Six/Switzerland"
   "FireFriend"
   "Fleeting Joys"
   "Forseti"
   "Frank Sinatra & Antônio Carlos Jobim"
   "Franz Ferdinand"
   "Fu Manchu"
   "Galaxie 500/On Fire"
   "Godspeed You! Black Emperor/'Allelujah! Don't Bend! Ascend!"
   "Godspeed You! Black Emperor/F#A#∞"
   "Grandaddy"
   "Grass Widow"
   "Household"
   "Insta"
   "Japancakes"
   "Jason Lytle"
   "Kings Of Convenience"
   "Komeda/Kokomemedada"
   "Komeda/What Makes It Go_"
   "Kyuss"
   "LCD Soundsystem"
   "Lacrosse"
   "Lady GaGa"
   "Land Of Talk"
   "Laura Veirs"
   "Le Futur Pompiste/Your Stories And Your Thoughts"
   "Le Tigre/Le Tigre"
   "Low/I Could Live In Hope"
   "Low/Live at Eindhoven"
   "Low/The Great Destroyer"
   "Low/Things We Lost In The Fire"
   "Lucy Van Pelt"
   "Lush/Gala"
   "Lush/Last Night"
   "Lush/Lovelife"
   "Lush/Split"
   "Lush/Spooky"
   "Lush/Topolino"
   "Mahogany"
   "Master Musicians of Bukakke/Totem One"
   "Mazinga Phaser"
   "Me You Us Them"
   "Monzy"
   "My Bloody Valentine/Loveless"
   "My Penis is Made of Dogshit"
   "Nerdkern"
   "Neutral Milk Hotel"
   "Nirvana/Nevermind"
   "Parquet Courts"
   "Pavement"
   "Philip Glass"
   "Pia Fraus"
   "Pink Floyd"
   "Pinkshinyultrablast"
   "Pixies"
   "Projekt A-KO"
   "Red Sparowes"
   "Ride"
   "S"
   "Sciflyer"
   "Silver Jews"
   "Slowdive/Souvlaki"
   "Speedy Ortiz"
   "Stan Getz & Charlie Byrd"
   "Stan Getz & João Gilberto"
   "Stan Getz"
   "Stephen Malkmus"
   "Stereolab"
   "Swearin'"
   "Swervedriver/Ejector Seat Reservation"
   "Swervedriver/Never Lose That Feeling"
   "Swervedriver/Raise"
   "Tacocat"
   "Talking Heads"
   "Tame Impala"
   "Teenage Cool Kids"
   "The Apples in Stereo"
   "The Apples in stereo"
   "The Appleseed Cast"
   "The Boo Radleys/Everything's Alright Forever"
   "The Boo Radleys/Ichabod and I"
   "The Breeders"
   "The Brian Jonestown Massacre/Methodrone"
   "The Brian Jonestown Massacre/Take It From The Man"
   "The Depreciation Guild"
   "The Ecstasy of Saint Theresa"
   "The Greenhornes"
   "The High Water Marks"
   "The Horrorist"
   "The Hot Toddies/Smell The Mitten"
   "The Limiñanas"
   "The Moldy Peaches"
   "The Notorious B.I.G_/Ready To Die (The Remaster)"
   "The Organ"
   "The Presidents of the United States of America"
   "The Stooges"
   "The Strokes"
   "The Swirlies"
   "The Tobasco Donkeys"
   "The Trotter Trio"
   "The White Stripes"
   "Tiger Trap"
   "Tim Gane & Sean O'Hagan"
   "Truckfighters"
   "Urusei Yatsura"
   "Volkolak"
   "Walter Wanderley"
   "Weezer"
   "Yo La Tengo"
   "Yuck"
   "advantage Lucy"
   "beulah"
   "capsule"
   "she"
)

for f in "${artists[@]}"; do
   mkdir -p "$DEST/$f"
   rsync -av "$SRC/$f/" "$DEST/$f"
done

echo "Dont forget to sudo fatsort -cn /dev/disk1s1"
